version: '2.4'

services:
  lambda-runtime:
    image: cloudfuse-lab-arrow-cpp-build-bee
    volumes:
      - ${CURDIR}/bin/build-amznlinux1:/build
    entrypoint: ${VALGRIND_CMD} /build/executables/cloudfuse-lab-${BUILD_FILE}-static