version: '2.4'

services:
  lambda-runtime:
    image: buzz-lambda-runtime-cpp
    volumes:
      - ~/.aws:/root/.aws
    cpus: 1
    mem_limit: 2048M
    environment:
      VALGRIND_CMD: ${VALGRIND_CMD}

