version: '2.4'

services:
  lambda-emulator:
    image: buzz-amznlinux1-run-cpp
    build:
      context: ../../bin/build-amznlinux1/buzz
      dockerfile: ../../../docker/amznlinux1-run-cpp/runtime.Dockerfile
      args:
        BUILD_FILE: ${BUILD_FILE}
    volumes:
      - ~/.aws:/root/.aws
    cpus: 1
    mem_limit: 2048M
    environment:
      VALGRIND_CMD: ${VALGRIND_CMD}

