version: '2.4'

services:
  minio:
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    volumes:
      - ~/workspace/data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - backend

  proxy:
    build:
      context: .
      dockerfile: ./proxy-nginx.Dockerfile # nginx seems to behave better when increasing bandwidth throttling
    ports:
      - 8080:9000
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      frontend:
        aliases:
          - minio
      backend:

  lambda-runtime:
    image: buzz-lambda-runtime-cpp
    volumes:
      - ~/.aws:/root/.aws
    cpus: 1
    mem_limit: 2048M
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      VALGRIND_CMD: ${VALGRIND_CMD}
    depends_on:
      proxy:
        condition: service_healthy
    networks:
      - frontend

# use networks to have the same hostname for proxy and minio
# necessary because "host" header is signed by the SDK
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge