version: '2.4'

services:
  lambda-runtime:
    image: buzz-arrow-cpp-build-bee
    volumes:
      - ${CURDIR}/bin/build-amznlinux1:/build
    entrypoint: ${VALGRIND_CMD} /build/executables/buzz-${BUILD_FILE}-static