version: '2.4'

services:
  lambda-runtime:
    image: buzz-arrow-cpp-build-bee
    volumes:
      - ${CURDIR}/bin/build-amznlinux1:/build
    entrypoint: /build/executables/buzz-${BUILD_FILE}-static
    environment:
      VALGRIND_CMD: ${VALGRIND_CMD}