version: '2.4'

services:
  minio:
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    volumes:
      - ~/workspace/data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 1s
      retries: 10
  
  test:
    image: buzz-amznlinux1-run-cpp
    volumes:
      - ~/.aws:/root/.aws
    environment:
      AWS_ACCESS_KEY: minio
      AWS_SECRET_KEY: minio123
      BUILD_TYPE: static
    depends_on:
      minio:
        condition: service_healthy